### PR TITLE
Converted all icons to webp and added migration step

### PR DESCRIPTION
**Pull request by rrenna**
Leaving as draft until I've tested more, but I'm pretty confident this works as designed.

### CODE REVIEW

**Comment by rrenna** [comment]
I've tested this a half dozen times, and @ThroughlyDruxy has independently confirmed on his side.

**Comment by rrenna** [comment]
Converting back to draft, as I'd like to re-convert some icons to be higher quality.

**Comment by rrenna** [comment]
Re-encoded webp files at 90% quality without any downscaling.

**Comment by rrenna** [comment]
Fixed merge conflicts.

**Comment by wildj79** [comment]
As much as I want to include this one in the next release, I think it's best we wait. I want the next release to be as stable as possible, since it'll be the last update for Foundry v0.7.x. Once we've gotten past the v0.8.x update, then we'll revisit this.

**Comment by TimToxopeus** [comment]
Another task lingering in Pull Request limbo, one that needs a bit of gentle re-loving I think?

**Comment by TimToxopeus** [comment]
Updated the branch on my side, will merge it Soon™.

**Pull request merged**
