### PR TITLE
Translation fr

### PR DESCRIPTION
**Pull request by decad7never**
Drone translation
add missing translation key (drone) like unity for french translation
rework on fr translation from users feedbacks

### CODE REVIEW

**Comment by TimToxopeus** [comment]
I have one suggestion, please move the unit in localization from SFRPG.DroneSheet.Speed into a separate category. Something like SFRPG.Units.Feet, SFRPG.Units.Metric, etc.

This will allow us to use units and unit conversions in other places than just the DroneSheet, even if it's only the drone sheet that supports it.

**Comment by decad7never** [comment]
Its done i have made the modification with "SRFPG.Unity.Speed"

**Comment by decad7never** [comment]
Move to SRFPG.Units.Speed

**Comment by wildj79** [comment]
You missed changing it on `ja.json`, also, could you move SFRPG.Units.Speed to above the SFRPG.LocalizationTerminator field?

**Comment by decad7never** [comment]
Its ok now. ja translation added, and i have change the position of the new translation key above the SFRPG.LocalizationTerminator field

**Pull request merged**
