### PR TITLE
Add icons for each feats inside the compendium

### PR DESCRIPTION
**Pull request by decad7never**
All icons come from the humble pack

### CODE REVIEW

**Comment by TimToxopeus** [comment]
I spotted a few typos in the filenames:
deflect_projectifles.png should be deflect_projectiles.png
diverse_conditionning.png should be diverse_conditioning.png
pdychic_sense.PNG should be psychic_sense.png
survivaliste.PNG should be survivalist.png
weapon_specialisation.png should be weapon_specialization.png

I also noticed the extension's capitalization is inconsistent, some files are PNG and others are png. It doesn't carry a major impact on Windows filesystems, but it may carry unintended side-effects on Unix systems, should Foundry ever support it. If you could make sure all extensions are lowercase, that would be great.

**Comment by decad7never** [comment]
I have tested this pack on debian system and all works correctly, but i can do the modification this night. replace PNG to png and do the correction also about typos miss.

**Comment by decad7never** [comment]
All modifications are Ok now.

**Comment by TimToxopeus** [comment]
pdychic_sense.png still has a typo.

**Comment by decad7never** [comment]
i have fixed a cache issue inside the compendium db, its ok now.

**Comment by TimToxopeus** [comment]
Mergin'. :)

**Pull request merged**
