### PR TITLE
Implement Gunnery skill for NPC Starships

### PR DESCRIPTION
**Pull request by LebombJames**
I've seen that setting up NPC gunners is a frequent issue for some users on the discord, so I cooked this up to alleviate it. Just wanna gauge feedback for now, see if this is appropriate for the system. I was also thinking the calculation could be the max of the modifier and ranks, in order to not break existing NPC ships.

### CODE REVIEW

**Comment by TimToxopeus** [comment]
I'm not sure this is correct behavior. Piloting mod is for piloting checks only, piloting ranks or BAB is for attacks. But allowing piloting mod you create a situation where the wrong value could be used. A better way would be to figure out how to rename the piloting ranks field into "Gunnery bonus" for NPCs specifically.

**Comment by LebombJames** [comment]
image
Ok, got the ranks column to show "Gunnery Modifier" for only gunners. The issue with this however is that the column heading is incorrect if the gunner has any other skills.

image
I also started working on adding "gunnery" as a selectable skill and got it half-working, but it still has the issue of the column heading being incorrect. This method would still require an if statement on the `parts` declaration to use the gunnery "skill" modifier for NPC ship attacks. (I suppose you could use the modifier column for the bonus, as the language is slightly more intuitive)

We've got three different implementations here all with different pros and cons, but I think the pseudo-gunnery skill is the best.

**Comment by LebombJames** [comment]
image
image

Got a gunnery skill working, left max(piloting ranks/gunnery mod) in for backwards compatability

**Comment by LebombJames** [comment]
Wrote a migration, will set gunnery mod equal to piloting ranks, then remove the piloting entry.

**Comment by LebombJames** [comment]
Aha, there's an issue for this. Closes #458

**Comment by TimToxopeus** [comment]
I have nothing big to complain about, great work! :)

**Pull request merged**
