### PR TITLE
Manifest+ Authors section

### PR DESCRIPTION
**Pull request by trechriron**
Added the manifest+ authors section so all contributors can include info if they want.

### CODE REVIEW

**Comment by rrenna** [comment]
There's overlap with my manifest+ PR.

**Comment by wildj79** [comment]
@rrenna Actually, you updated the wrong file in your PR. 😄

**Comment by rrenna** [comment]
Whoops!

**Comment by rrenna** [comment]
If we merge this instead can we add Deepflame as an author.

**Comment by wildj79** [comment]
Yep. Could also add an entry for yourself 😉 .

**Comment by rrenna** [comment]
Well I did, but apparently in the wrong file 😜

**Comment by wildj79** [comment]
This one's pretty straight forward, so I'm going to merge it. @rrenna once it's merged, go ahead and submit a new PR with the needed info for yourself and Deepflame.

**Pull request merged**
