### PR TITLE
Item types

### PR DESCRIPTION
**Pull request by CptTwinkie**
New and missing item types
• Shields

### CODE REVIEW

**Comment by CptTwinkie** [comment]
Shields added (no localization yet)

Asking for feedback

**Comment by CptTwinkie** [comment]
[[FEAT] Add shields as an item type.](https://trello.com/c/vlZklybz/67-feat-add-shields-as-an-item-type)

**Comment by CptTwinkie** [comment]
[[FEAT] Add ammunition as an item type.](https://trello.com/c/givnQMK9/59-feat-add-ammunition-as-an-item-type)

**Comment by CptTwinkie** [comment]
[[FEAT] Add weapon upgrades as an item type.](https://trello.com/c/Ljz5HJsx/68-feat-add-weapon-upgrades-as-an-item-type)

**Comment by TimToxopeus** [comment]
Three requests :)
- There's a merge conflict, I have no idea how to resolve it in the github web editor, so could you take care of it?
- Please rename your localized keys that end on Tippy to Tooltip to make it consistent with the rest of the system.
- In the future, please split your work into smaller requests. This contains shields, some starship work, new item types, and a complete overhaul of localization. It makes it hard to review.

**Review by TimToxopeus — CHANGES_REQUESTED** [review]
A couple of requests:
- There's a merge conflict, I have no idea how to resolve it in the github web editor, so could you take care of it?
- Please rename your localized keys that end on Tippy to Tooltip to make it consistent with the rest of the system.
- In module/packs/equipment-browser.js can you add shield to the filters?
- Can you update the shield item jsons to have shield as a type and re-cook the equipment compendium?

In the future, please split your work into smaller pull requests. This contains shields, some starship work, new item types, and a complete overhaul of localization. It makes it harder to review.

**Comment by CptTwinkie** [comment]
- Updated with requested changes
- Added sturdy defaults for appropriate items
- Added weapon properties and set nonlethal enabled by default

**Review by TimToxopeus — APPROVED** [review]

**Comment by TimToxopeus** [comment]
All good, merging it now. :-)

**Pull request merged**
