### PR TITLE
Update Gulp workflow for Docker

### PR DESCRIPTION
**Pull request by trechriron**
Updated gulp.js and package.json with copy action vs. symlink. Docker hates symlinks. Also added a buildDock and cleanDock command for easier usage and avoid impacting the current workflow.

### CODE REVIEW

**Comment by wildj79** [comment]
The PR looks fine, and I don't have any issues with merging this. But, I am curious as to its purpose? The gulp tasks, in general, aren't meant for mainstream consumption, there only meant to be used in development. Is there any particular reason you are setting this up for docker?

**Comment by trechriron** [comment]
I use Docker because I don't trust Windows to emulate the production infrastructure. I wanted it to run on the same server core. My hope would be to eliminate dev vs prod wonkiness. :-)

Docker hates symlinks, so I needed actual fs.copy operations. I didn't want to mess with the current workflow.

This could be useful for new devs looking to use Docker. There are several implementations out there for Foundry.

**Comment by rrenna** [comment]
Sounds interesting. Maybe if it's merged and works well you can amend the contributing documents with alternate setup instructions ?

**Comment by trechriron** [comment]
I would be happy to! I can include info and my docker-compose file.

**Comment by wildj79** [comment]
Ok, sounds good. Since this doesn't have any affect on our current development process, and it might be useful anyway, I'm going to go ahead and merge it.

**Pull request merged**
