### PR TITLE
Rebound Vanguard Aspect added + misc

### PR DESCRIPTION
**Pull request by tiapfy**
Added the Rebound Vanguard Aspect and its abilities. It's my first contribution to anything on git so I don't know if I did everything in the correct way.

### CODE REVIEW

**Comment by Iankid** [comment]
Nice.
Two notes things you can change;
1, The DB file is unnecessary in the commit. Wild does another cook before releasing, so that DB adds nothing to the commit, and potentially creates weirdness.
2, Aspect Insight (Ex). This is more encouraged then required. but the text "Improved Combat Maneuver (disarm)" could be turned into an item link.

**Comment by tiapfy** [comment]
Ok, I added the links to the improved combat maneuver feats to the insights and the main aspect features who lacked them. I also added the missing galactic magic disciplines.

**Comment by tiapfy** [comment]
I added the missing "Mutual Destruction" alternate class feature

**Comment by Iankid** [comment]
Hey. Was reading through the FAQ/Errata page on Paizo, and noted an Errata for Mutual Destruction.

"Page 36: At the end of the mutual destruction, add the following.
This alters entropic pool and mitigate, and it replaces invulnerability."

Would be good to get that added in, before this gets merged.

**Comment by tiapfy** [comment]
Done

**Comment by wildj79** [comment]
Thanks for the first time contribution! I'm gonna go ahead and merge this.

**Pull request merged**
